name: Build Images

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
